# Generated by Django 5.1.1 on 2024-09-27 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_hp', models.IntegerField()),
                ('max_hp', models.IntegerField()),
                ('ac', models.IntegerField()),
                ('attack', models.CharField(max_length=200)),
                ('status_effect', models.CharField(blank=True, max_length=100, null=True)),
                ('spells_abilities', models.CharField(blank=True, max_length=300, null=True)),
                ('initiative_order', models.IntegerField()),
                ('spell_slots', models.CharField(blank=True, max_length=100, null=True)),
                ('speed', models.IntegerField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='players',
            field=models.ManyToManyField(to='encounters.player'),
        ),
    ]
